<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-QWiki.Ingestion.Worker-8603758b-0a97-4f00-b519-fde74fc77e70</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QWiki.Ingestion\QWiki.Ingestion.csproj" />
    <ProjectReference Include="..\QWiki.Shared\QWiki.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.3.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.CosmosNoSql" Version="1.74.0-preview" />
  </ItemGroup>

</Project>
